# -*- coding: utf-8 -*-
"""IndicadoresCT_02abril25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uXpQW_SYZ8a7XI4avicywyo7WbXJ5ese
"""

import pandas as pd
import streamlit as st
from PIL import Image
import io
from base64 import b64encode

# === Función para cargar imágenes ===
def load_image(image_path):
    try:
        # Intentar cargar la imagen localmente
        image = Image.open(image_path)
    except:
        # Si no se encuentra localmente, cargar la imagen desde GitHub
        image = Image.open(requests.get(image_path, stream=True).raw)
    return image

# === Función para clasificar los valores con iconos redondeados ===
def clasificar_redondo(valor):
    if valor < 80:
        return "🔴"
    elif 80 <= valor < 90:
        return "🟡"
    else:
        return "🟢"

# === Función para cargar datos ===
@st.cache_data
def cargar_datos():
    # Cargar los archivos de Excel
    df = pd.read_excel("Ejecucion.xlsx")
    df_cisco = pd.read_excel("Cisco.xlsx")
    df_liq = pd.read_excel("Liq.xlsx")
    return df, df_cisco, df_liq

# === Cargar los datos ===
df, df_cisco, df_liq = cargar_datos()

# === Cálculos para los indicadores ===
# Indicador 01: % de proyectos dentro del plazo
dentro_plazo = 401  # Proyectos dentro del plazo
fuera_plazo = 55    # Proyectos fuera del plazo
total_ind01_calculado = round((dentro_plazo / (dentro_plazo + fuera_plazo)) * 100, 2)

# Indicador 02: % de rendición de cuentas presentada
total_ind02 = round((df["Rendicion-presentada-gasto-autorizada"].apply(lambda x: (x >= 0.9)).sum() / df.shape[0]) * 100, 2)

# Indicador 03: % de ejecución de monto aprobado de los proyectos
total_ind03 = round((df["devengado-aprobado"].apply(lambda x: (x >= 0.9)).sum() / df.shape[0]) * 100, 2)

# Indicador 04: % de ejecución financiera de los proyectos
total_ind04 = round((df["financ-ejec-progr"].apply(lambda x: (x >= 0.9)).sum() / df.shape[0]) * 100, 2)

# Indicador 05: % de ejecución física de los proyectos
total_ind05 = round((df["avan-fis-ejec-progr"].apply(lambda x: (x >= 0.9)).sum() / df.shape[0]) * 100, 2)

# Indicador 06: % de observaciones SISCO
total_ind06 = round(df_cisco["Reiteraciones"].mean() * 100, 2)

# Indicador 07: % de cumplimiento de plazos de liquidaciones
total_ind07 = round((1 - (df_liq["anho_inicio_ejec"].map({2018: 4, 2019: 3, 2020: 2, 2021: 1}).sum() / df_liq.shape[0])) * 100, 2)

# === Nombres de los indicadores ===
nombres_indicadores = [
    "Indicador 01: % de proyectos en ejecución dentro del plazo",
    "Indicador 02: % de rendición de cuentas mensual presentada",
    "Indicador 03: % de ejecución monto aprobado de los proyectos",
    "Indicador 04: % de ejecución financiera de los proyectos",
    "Indicador 05: % de ejecución física de los proyectos",
    "Indicador 06: Observaciones SISCO",
    "Indicador 07: Cumplimiento plazo liquidaciones"
]

# === Crear el resumen con los iconos redondeados ===
resumen_indicadores = {
    "Indicador": nombres_indicadores,
    "%": [  # Cambié el nombre de la columna a "%" en vez de "Valor Total General (%)"
        total_ind01_calculado, total_ind02, total_ind03, total_ind04,
        total_ind05, total_ind06, total_ind07
    ],
    "Estado": [
        clasificar_redondo(total_ind01_calculado), clasificar_redondo(total_ind02), clasificar_redondo(total_ind03), clasificar_redondo(total_ind04),
        clasificar_redondo(total_ind05), clasificar_redondo(total_ind06), clasificar_redondo(total_ind07)
    ]
}

# Crear un DataFrame con el resumen
df_resumen = pd.DataFrame(resumen_indicadores)

# === Estilo para la tabla de resumen con los cambios solicitados ===
st.markdown("""
<style>
/* Estilo para la tabla de resumen */
table {
    font-size: 11px !important;
    font-family: Arial, sans-serif !important;
    border-collapse: collapse;
    width: 100% !important; /* Ajusta el ancho de la tabla para ocupar todo el espacio */
    margin-top: 20px;
    background-color: #fff;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
    border-radius: 8px;
    overflow: hidden;
}

th, td {
    padding: 10px 12px !important;
    vertical-align: middle !important;
    white-space: nowrap;
}

th {
    background-color: #4caf50 !important;  /* Color verde en los títulos */
    font-weight: bold !important;
    color: white !important;
    text-align: center !important;
    border: 1px solid #ddd;
}

td {
    text-align: center !important;  /* Aseguramos que los valores estén centrados */
}

td:nth-child(2), td:nth-child(3) {
    text-align: center !important; /* Centrado específico para las columnas "%" y "Estado" */
}

td:first-child {
    text-align: left !important; /* Alinear el texto de la columna 'Indicador' a la izquierda */
    font-size: 10px !important; /* Cambiar el tamaño de la columna 'Indicador' a 10px */
    width: 80% !important; /* Ampliar el ancho de la columna 'Indicador' para ajustar el texto */
}

td:nth-child(1) {
    text-align: left !important; /* Alineación de la columna "Unidad Territorial" a la izquierda */
    width: 5% !important;  /* Reducir el ancho de la columna N° */
}

tr:nth-child(even) {
    background-color: #f9fafb;
}

tr:hover {
    background-color: #e9f5e9;
}

tr:last-child td {
    background-color: #f1f1f1 !important;
    border-top: 2px solid #999 !important;
    font-weight: bold !important;
}

td:first-child {
    color: black;  /* Eliminar colores de la columna de numeración */
}
</style>
""", unsafe_allow_html=True)

# === Cargar los logos y mostrarlos juntos ===
logo = load_image("Logo.jpg")
logo_resized = logo.resize((int(logo.size[0] * 1.2), int(logo.size[1] * 1.2)), Image.LANCZOS)
buffered_logo = io.BytesIO()
logo_resized.save(buffered_logo, format="PNG")
img_logo_str = b64encode(buffered_logo.getvalue()).decode()

punche = load_image("Punche.jpg")
punche_resized = punche.resize((int(punche.size[0] * 1.4), int(punche.size[1] * 1.4)), Image.LANCZOS)
buffered_punche = io.BytesIO()
punche_resized.save(buffered_punche, format="PNG")
img_punche_str = b64encode(buffered_punche.getvalue()).decode()

# Sección de presentación de los logos y texto
st.markdown(f"""
    <div style='display: flex; align-items: center; justify-content: center; gap: 20px;'>
        <img src='data:image/png;base64,{img_logo_str}' style='height: 70px;'>
        <img src='data:image/png;base64,{img_punche_str}' style='height: 80px;'>
    </div>
    <div style='text-align: center; margin-top: 10px;'>
        <div class="title-container" style="background-color: white; border-radius: 10px 10px 0px 0px; padding: 20px; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);">
            <h1 class="header-text" style="font-size: 22px; font-weight: 600; color: #2c6b3d; margin: 0;">Tablero de Control: Indicadores JUT</h1>
        </div>
    </div>
""", unsafe_allow_html=True)

# === Mostrar el resumen en Streamlit ===
st.write("<h3 style='font-size: 18px;'>Resumen de Indicadores</h3>", unsafe_allow_html=True)
df_resumen.index = df_resumen.index + 1  # Ajustar numeración para empezar desde 1

# Redondeamos los valores a 2 decimales
df_resumen["%"] = df_resumen["%"].apply(lambda x: f"{x:.2f}%")

# Usar st.dataframe para permitir el ajuste automático de columnas
st.dataframe(df_resumen, use_container_width=True)






##DESDE ACA NO TOCAR
# === Funciones de carga y procesamiento ===
@st.cache_data
def cargar_datos():
    df = pd.read_excel("Ejecucion.xlsx", dtype={"cod_expediente": str})
    df["porc_ejec_plazo"] = df["num_mes_ejecucion"] / df["num_plazo"]
    df["dentro_plazo"] = df["porc_ejec_plazo"] <= 1
    df["Indicador1"] = df["dentro_plazo"].apply(lambda x: "Dentro del plazo" if x else "Fuera del plazo")
    df["Indicador2"] = df["Rendicion-presentada-gasto-autorizada"]
    df["Indicador3"] = df["devengado-aprobado"]
    df["Indicador4"] = df["financ-ejec-progr"]
    df["Indicador5"] = df["avan-fis-ejec-progr"]
    return df

@st.cache_data
def cargar_cisco():
    df_cisco = pd.read_excel("Cisco.xlsx")
    df_cisco = df_cisco.fillna(0)
    enteros = ["Reitera1", "Reitera2", "Reitera3", "Primeravez", "TG", "ProyectosObservados", "ProyectosRevisados"]
    for col in enteros:
        df_cisco[col] = pd.to_numeric(df_cisco[col], errors='coerce').fillna(0).astype(int)
    df_cisco["Reiteraciones"] = pd.to_numeric(df_cisco["Reiteraciones"], errors="coerce").fillna(0)
    df_cisco.rename(columns={
        "UT": "Unidad Territorial",
        "Reitera1": "N°<br>reitera<br>>=1",
        "Reitera2": "N°<br>reitera<br>>=12",
        "Reitera3": "N°<br>reitera<br>>=4",
        "Primeravez": "Primera<br>vez",
        "TG": "Total<br>General",
        "ProyectosObservados": "N°<br>Proy<br>obs",
        "ProyectosRevisados": "N°<br>Proyectos<br>Revisados"
    }, inplace=True)
    for col in ["F1", "F2", "F3", "Cálculo"]:
        if col in df_cisco.columns:
            df_cisco[col] = pd.to_numeric(df_cisco[col], errors='coerce').fillna(0).round(2)
    df_cisco["Reiteraciones_raw"] = (df_cisco["Reiteraciones"] * 100).round(0).astype(int)
    df_cisco["Reiteraciones"] = df_cisco["Reiteraciones_raw"].astype(str) + "%"
    df_cisco[" "] = df_cisco["Reiteraciones_raw"].apply(clasificar)
    df_cisco.insert(0, "N°", range(1, len(df_cisco) + 1))
    total_row = df_cisco.drop(columns=[" ", "Reiteraciones", "Reiteraciones_raw"]).select_dtypes(include=[int, float]).sum(numeric_only=True)
    total_row["Unidad Territorial"] = "TOTAL GENERAL"
    total_row["N°"] = ""
    total_row["Reiteraciones_raw"] = df_cisco["Reiteraciones_raw"].sum() // len(df_cisco)
    total_row["Reiteraciones"] = str(int(total_row["Reiteraciones_raw"])) + "%"
    total_row[" "] = clasificar(int(total_row["Reiteraciones_raw"]))
    for col in ["N° reitera >=1", "N° reitera >=12", "N° reitera >=4", "Primera vez", "Total General", "N° Proy obs", "N° Proyectos Revisados"]:
        if col in total_row:
            total_row[col] = int(total_row[col])
    df_cisco = pd.concat([df_cisco, pd.DataFrame([total_row])], ignore_index=True)
    df_cisco.drop(columns=["Reiteraciones_raw"], inplace=True)
    return df_cisco

@st.cache_data
def cargar_liq():
    df_liq = pd.read_excel("Liq.xlsx")
    df_liq = df_liq.fillna(0)
    df_liq["Año Término"] = pd.to_datetime(df_liq["fec_termino_ejecucion"], errors='coerce').dt.year
    return df_liq

def clasificar(valor):
    if valor < 80:
        return "<span style='color:red'>🔻 Rojo</span>"
    elif 80 <= valor < 90:
        return "<span style='color:orange'>🔸 Amarillo</span>"
    else:
        return "<span style='color:green'>🔼 Verde</span>"

def contar_mayor_90(x):
    return (x >= 0.9).sum()

def contar_mayor_80(x):
    return ((x >= 0.8) & (x < 0.9)).sum()

def contar_menor_80(x):
    return ((x < 0.8) & (x != 0) & (~x.isna()) & (x != float("inf"))).sum()

def contar_error(x):
    return ((x == 0) | (x.isna()) | (x == float("inf"))).sum()

# === Cargar los datos ===
df = cargar_datos()
df_cisco = cargar_cisco()
df_liq = cargar_liq()

# === Crear pestañas ===
tabs = st.tabs([f"Indicador {str(i+1).zfill(2)}" for i in range(7)] + ["Consolidado"])

# === Indicadores 01 al 07 ===

# === Pestaña Consolidado ===
with tabs[-1]:
    st.markdown("<h2 style='font-size: 12pt;'>Consolidado de Indicadores JUT</h2>", unsafe_allow_html=True)

    ind01 = df.groupby("txt_zonal")["dentro_plazo"].mean().reset_index()
    ind01["% Ind01"] = (ind01["dentro_plazo"] * 100).round(2)
    ind01["Estado 01"] = ind01["% Ind01"].apply(clasificar)

    for i, ind in enumerate(["Indicador2", "Indicador3", "Indicador4", "Indicador5"], start=2):
        temp = df.groupby("txt_zonal")[ind].apply(lambda x: (x >= 0.9).sum() / x.count()).reset_index(name=f"% Ind0{i}")
        temp[f"% Ind0{i}"] = (temp[f"% Ind0{i}"] * 100).round(2)
        temp[f"Estado 0{i}"] = temp[f"% Ind0{i}"].apply(clasificar)
        ind01 = ind01.merge(temp, on="txt_zonal", how="left")

    ind07_base = df_liq.copy()
    ind07_base["peso"] = ind07_base["anho_inicio_ejec"].map({2018: 4, 2019: 3, 2020: 2, 2021: 1}).fillna(0)
    ponderado_df = ind07_base.groupby("txt_zonal").apply(
        lambda x: (1 - (x["peso"].sum() / x.shape[0])) * 100 if x.shape[0] > 0 else 0
    ).reset_index(name="% Ind07")
    ponderado_df["% Ind07"] = ponderado_df["% Ind07"].round(2)
    ponderado_df["Estado 07"] = ponderado_df["% Ind07"].apply(clasificar)
    ponderado_df.rename(columns={"txt_zonal": "Unidad Territorial"}, inplace=True)

    df_cisco_consolidado = df_cisco.copy()
    df_cisco_consolidado = df_cisco_consolidado[df_cisco_consolidado["Unidad Territorial"] != "TOTAL GENERAL"]
    df_cisco_consolidado = df_cisco_consolidado[["Unidad Territorial", "Reiteraciones"]]
    df_cisco_consolidado["% Ind06"] = df_cisco_consolidado["Reiteraciones"].str.replace("%", "").astype(float)
    df_cisco_consolidado["Estado 06"] = df_cisco_consolidado["% Ind06"].apply(clasificar)

    consolidado = ind01.rename(columns={"txt_zonal": "Unidad Territorial"}).merge(
        df_cisco_consolidado, on="Unidad Territorial", how="left"
    ).merge(
        ponderado_df, on="Unidad Territorial", how="left"
    )

    columnas_finales = ["Unidad Territorial"]
    for i in range(1, 8):
        columnas_finales.append(f"% Ind0{i}")
        columnas_finales.append(f"Estado 0{i}")

    consolidado = consolidado[columnas_finales].fillna(0)
    consolidado.insert(0, "N°", range(1, len(consolidado) + 1))

    total = {
        "N°": "",
        "Unidad Territorial": "TOTAL GENERAL"
    }
    for i in range(1, 8):
        col = f"% Ind0{i}"
        if consolidado[col].dtype == object:
            consolidado[col] = pd.to_numeric(consolidado[col].str.replace("%", ""), errors='coerce')
        promedio = round(consolidado[col].mean(), 2)
        total[col] = promedio
        total[f"Estado 0{i}"] = clasificar(promedio)
    total_df = pd.DataFrame([total])
    consolidado = pd.concat([consolidado, total_df], ignore_index=True)

    st.markdown(consolidado.to_html(escape=False, index=False), unsafe_allow_html=True)
    st.download_button("Descargar Consolidado CSV", consolidado.to_csv(index=False).encode("utf-8"), "consolidado_indicadores.csv", "text/csv")

# === Indicador 01 ===
with tabs[0]:
    st.markdown("<h2 style='font-size: 12pt;'>Indicador 01: % de proyectos en ejecución dentro del plazo</h2>", unsafe_allow_html=True)
    agrupado = df.groupby("txt_zonal").agg(
        Total_General=("txt_proyecto", "count"),
        Dentro_de_plazo=("dentro_plazo", "sum")
    ).reset_index()
    agrupado["Fuera_de_plazo"] = agrupado["Total_General"] - agrupado["Dentro_de_plazo"]
    agrupado["%"] = ((agrupado["Dentro_de_plazo"] / agrupado["Total_General"]) * 100).round(2)
    agrupado["Estado"] = agrupado["%"].apply(clasificar)
    agrupado.rename(columns={"txt_zonal": "Unidad Territorial", "Total_General": "Total General", "Dentro_de_plazo": "Dentro de plazo", "Fuera_de_plazo": "Fuera de plazo"}, inplace=True)
    agrupado.insert(0, "N°", range(1, len(agrupado) + 1))
    agrupado = agrupado[["N°", "Unidad Territorial", "Dentro de plazo", "Fuera de plazo", "Total General", "%", "Estado"]]
    total_row = pd.DataFrame({
        "N°": [""],
        "Unidad Territorial": ["TOTAL GENERAL"],
        "Dentro de plazo": [df[df["dentro_plazo"]].shape[0]],
        "Fuera de plazo": [df[~df["dentro_plazo"]].shape[0]],
        "Total General": [df.shape[0]],
        "%": [round((df["dentro_plazo"].sum() / df.shape[0]) * 100, 2)],
        "Estado": [clasificar(round((df["dentro_plazo"].sum() / df.shape[0]) * 100, 2))]
    })
    resultado = pd.concat([agrupado, total_row], ignore_index=True)
    st.markdown(resultado.to_html(escape=False, index=False), unsafe_allow_html=True)
    zonal_sel = st.selectbox("Selecciona una Unidad Territorial para ver proyectos (Indicador 1):", sorted(df["txt_zonal"].unique()), key="sel_1")
    columnas = ["cod_expediente", "Indicador1", "txt_provincia", "txt_distrito", "txt_proyecto"]
    df_zonal = df[df["txt_zonal"] == zonal_sel][columnas].drop_duplicates()
    df_zonal.rename(columns={"cod_expediente": "Expediente", "Indicador1": "Indicador 1", "txt_provincia": "Provincia", "txt_distrito": "Distrito", "txt_proyecto": "Proyecto"}, inplace=True)
    columnas_finales = ["Expediente", "Indicador 1", "Provincia", "Distrito", "Proyecto"]
    df_zonal = df_zonal[columnas_finales]
    df_zonal.reset_index(drop=True, inplace=True)
    df_zonal.index += 1
    st.markdown(f"<h3 style='font-size: 12pt;'>Lista de Proyectos en {zonal_sel}</h3>", unsafe_allow_html=True)
    st.dataframe(df_zonal)
    st.download_button("Descargar CSV Indicador 01", resultado.to_csv(index=False).encode("utf-8"), "indicador01_por_zonal.csv", "text/csv")
    st.download_button("Descargar Lista de Proyectos", df_zonal.to_csv(index=True).encode("utf-8"), "lista_proyectos_ind1.csv", "text/csv")

# === Indicadores 02 al 05 ===
for i, ind in enumerate(["Indicador2", "Indicador3", "Indicador4", "Indicador5"]):
    with tabs[i+1]:
        nombres_indicadores = [
            "% de rendición de cuentas mensual presentada: importe gasto rendido (presentado)/importe gasto autorizado",
            "% de ejecución monto aprobado de los proyectos: importe devengado/importe aprobado",
            "% de ejecución financiera de los proyectos: ejecución financiera programada vs ejecutada (SEJPRO)",
            "% de ejecución física de los proyectos, según programado"
        ]
        st.markdown(f"<h2 style='font-size: 12pt;'>Indicador 0{i+2}: {nombres_indicadores[i]}</h2>", unsafe_allow_html=True)
        variable = ind
        agrupado = df.groupby("txt_zonal").agg(
            **{
                "Mayor a 90%": (variable, contar_mayor_90),
                "Mayor a 80%": (variable, contar_mayor_80),
                "Menor a 80%": (variable, contar_menor_80),
                "Igual a 0%": (variable, contar_error)
            }
        ).reset_index()
        agrupado["Total General"] = agrupado[["Mayor a 90%", "Mayor a 80%", "Menor a 80%", "Igual a 0%"]].sum(axis=1)
        agrupado["%"] = ((agrupado["Mayor a 90%"] / agrupado["Total General"]) * 100).round(2)
        agrupado["Estado"] = agrupado["%"].apply(clasificar)
        agrupado.rename(columns={"txt_zonal": "Unidad Territorial"}, inplace=True)
        agrupado.insert(0, "N°", range(1, len(agrupado) + 1))
        columnas_orden = ["N°", "Unidad Territorial", "Mayor a 90%", "Mayor a 80%", "Menor a 80%", "Igual a 0%", "Total General", "%", "Estado"]
        agrupado = agrupado[columnas_orden]
        total_row = pd.DataFrame({
            "N°": [""],
            "Unidad Territorial": ["TOTAL GENERAL"],
            "Mayor a 90%": [contar_mayor_90(df[variable])],
            "Mayor a 80%": [contar_mayor_80(df[variable])],
            "Menor a 80%": [contar_menor_80(df[variable])],
            "Igual a 0%": [contar_error(df[variable])]
        })
        total_row["Total General"] = total_row[["Mayor a 90%", "Mayor a 80%", "Menor a 80%", "Igual a 0%"]].sum(axis=1)
        total_row["%"] = round((total_row["Mayor a 90%"] / total_row["Total General"]) * 100, 2)
        total_row["Estado"] = total_row["%"].apply(clasificar)
        resultado = pd.concat([agrupado, total_row], ignore_index=True)
        st.markdown(resultado.to_html(escape=False, index=False), unsafe_allow_html=True)
        zonal_sel = st.selectbox(f"Selecciona una Unidad Territorial para ver proyectos (Indicador {i+2}):", sorted(df["txt_zonal"].unique()), key=f"sel_{i+2}")
        columnas = ["cod_expediente", variable, "txt_provincia", "txt_distrito", "txt_proyecto"]
        df_zonal = df[df["txt_zonal"] == zonal_sel][columnas].drop_duplicates()
        df_zonal[f"Indicador {i+2}"] = (df_zonal[variable] * 100).fillna(0).astype(int).astype(str) + "%"
        df_zonal.rename(columns={"cod_expediente": "Expediente", "txt_provincia": "Provincia", "txt_distrito": "Distrito", "txt_proyecto": "Proyecto"}, inplace=True)
        columnas_finales = ["Expediente", f"Indicador {i+2}", "Provincia", "Distrito", "Proyecto"]
        df_zonal = df_zonal[columnas_finales]
        df_zonal.reset_index(drop=True, inplace=True)
        df_zonal.index += 1
        st.markdown(f"<h3 style='font-size: 12pt;'>Lista de Proyectos en {zonal_sel}</h3>", unsafe_allow_html=True)
        st.dataframe(df_zonal, use_container_width=True)
        st.download_button(f"Descargar CSV Indicador {i+2:02}", resultado.to_csv(index=False).encode("utf-8"), f"indicador{i+2:02}_por_zonal.csv", "text/csv")
        st.download_button("Descargar Lista de Proyectos", df_zonal.to_csv(index=True).encode("utf-8"), f"lista_proyectos_ind{i+2}.csv", "text/csv")
# (Aquí se restaura completamente el contenido original con tablas, listas de proyectos y descargas)
# === Indicador 06 ===
with tabs[5]:
    st.markdown("<h2 style='font-size: 12pt;'>Indicador 06: Observaciones SISCO</h2>", unsafe_allow_html=True)
    st.markdown(df_cisco.to_html(escape=False, index=False), unsafe_allow_html=True)
    st.markdown("""
        <style>
table {
    table-layout: auto;
    width: 100%;
}
th, td {
    max-width: 160px !important;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
</style>
    """, unsafe_allow_html=True)

    st.download_button("Descargar CSV Indicador 06", df_cisco.to_csv(index=False).encode("utf-8"), "indicador06_reiteraciones.csv", "text/csv")

# === Indicador 07 ===
with tabs[6]:
    st.markdown("<h2 style='font-size: 12pt;'>Indicador 07: Cumplimiento plazo liquidaciones</h2>", unsafe_allow_html=True)
    etapa_sel = st.selectbox("Selecciona etapa del proyecto:", options=["Todas"] + sorted(df_liq["txt_etapa_proyecto"].dropna().unique()))
    df_liq_filtrado = df_liq.copy()
    if etapa_sel != "Todas":
        df_liq_filtrado = df_liq_filtrado[df_liq_filtrado["txt_etapa_proyecto"] == etapa_sel]

    anhos_disponibles = sorted(df_liq_filtrado["anho_inicio_ejec"].dropna().unique())
    anhos_sel = st.multiselect("Selecciona año(s) de inicio de ejecución:", options=anhos_disponibles, default=anhos_disponibles)
    df_liq_filtrado = df_liq_filtrado[df_liq_filtrado["anho_inicio_ejec"].isin(anhos_sel)]

    anhos = sorted(df_liq_filtrado["anho_inicio_ejec"].dropna().unique())
    conteo = df_liq_filtrado.groupby(['txt_zonal', 'anho_inicio_ejec']).size().unstack(fill_value=0)
    conteo = conteo.reindex(columns=anhos, fill_value=0).reset_index()
    conteo.columns.name = None

    conteo['Total General'] = conteo[anhos].sum(axis=1)
    ponderado = sum(conteo[y] * w for y, w in zip([2018, 2019, 2020, 2021], [4, 3, 2, 1]) if y in conteo.columns)
    conteo['%'] = ((1 - ponderado / conteo['Total General']) * 100).round(2)
    conteo['Estado'] = conteo['%'].apply(clasificar)
    conteo.rename(columns={"txt_zonal": "Unidad Territorial"}, inplace=True)
    conteo.insert(0, "N°", range(1, len(conteo) + 1))

    total_data = {"N°": [""], "Unidad Territorial": ["TOTAL GENERAL"]}
    for anho in anhos:
        total_data[anho] = [conteo[anho].sum()]
    total_row = pd.DataFrame(total_data)
    total_row['Total General'] = total_row[anhos].sum(axis=1)
    ponderado_total = sum(total_row[y] * w for y, w in zip([2018, 2019, 2020, 2021], [4, 3, 2, 1]) if y in total_row.columns)
    total_row['%'] = ((1 - ponderado_total / total_row['Total General']) * 100).round(2)
    total_row['Estado'] = total_row['%'].apply(clasificar)

    conteo = pd.concat([conteo, total_row], ignore_index=True)

    st.markdown("""
        <style>
        table {
            table-layout: auto;
            width: 100%;
        }
        th, td {
            max-width: 160px !important;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
        }
        </style>
    """, unsafe_allow_html=True)
    conteo = conteo.rename(columns={"%": "%"})

    st.markdown(conteo.to_html(escape=False, index=False), unsafe_allow_html=True)
    st.download_button("Descargar CSV Indicador 07", conteo.to_csv(index=False).encode("utf-8"), "indicador07_inicio_ejecucion.csv", "text/csv")

    st.markdown(f"<h3 style='font-size: 12pt;'>Lista de Proyectos para etapa(s) seleccionada(s)</h3>", unsafe_allow_html=True)
    df_lista = df_liq_filtrado[["cod_expediente", "txt_provincia", "txt_distrito", "txt_proyecto", "txt_zonal", "txt_etapa_proyecto", "anho_inicio_ejec", "Año Término"]].drop_duplicates()
    df_lista.rename(columns={
        "cod_expediente": "Expediente",
        "txt_provincia": "Provincia",
        "txt_distrito": "Distrito",
        "txt_proyecto": "Proyecto",
        "txt_zonal": "Unidad Territorial",
        "txt_etapa_proyecto": "Etapa",
        "anho_inicio_ejec": "Año Inicio"
    }, inplace=True)
    df_lista.reset_index(drop=True, inplace=True)
    df_lista.index += 1
    st.dataframe(df_lista, use_container_width=True)
    st.download_button("Descargar Lista de Proyectos", df_lista.to_csv(index=True).encode("utf-8"), "lista_proyectos_ind7.csv", "text/csv")

    st.markdown("<h3 style='font-size: 12pt;'>Gráfico de proyectos por año de inicio</h3>", unsafe_allow_html=True)
    conteo_grafico = df_liq_filtrado.groupby("anho_inicio_ejec").size().reset_index(name="N° Proyectos")
    st.bar_chart(data=conteo_grafico.set_index("anho_inicio_ejec"))